### ISSUE TITLE
Add radio button group for choosing a 3x3 language

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/content-validation-app#5]
Allow the user to choose the target language for the validator using a radio button group.

The languages/orgs are:
Russian (RU)/ru_gl
Hindi (HI)/translationCore-Create-BCS
Kannada (KN)/translationCore-Create-BCS
Latin-American Spanish (ES-419)/Es-419_gl

**Comment by mandolyte** [comment]
@birchamp  I need the orgs as well (unless they are all unfoldingWord).

**Comment by mandolyte** [comment]
Looking around in DCS, I find:

- ru_gl (Russian?)
- vi_gl (Hindi?)
- nothing obvious to me for Kannada
- Es-419_gl (in the orgname, the letter "E" may need to be changed to lowercase, but not sure)

**Comment by mandolyte** [comment]
Closing based on PR#6.
